"""create messages table

Revision ID: 02d4cee521cf
Revises: ba8bc4955295
Create Date: 2025-09-22 12:15:08.041119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02d4cee521cf'
down_revision = 'ba8bc4955295'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'updated_at')
    op.drop_column('messages', 'created_at')
    op.drop_column('messages', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('username', sa.VARCHAR(), nullable=False))
    op.add_column('messages', sa.Column('created_at', sa.DATETIME(), nullable=True))
    op.add_column('messages', sa.Column('updated_at', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###
